### ISSUE TITLE
 Address comments from the project presentation

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2023_Analysis_03-visual#6]
I will use this issue to track progress on the comments from earlier today. Feel free to close this issue once it has been resolved.

Additionally, please submit a PR with any problems or useful info you uncovered in the FAQ repository I created: https://github.com/MATF-Software-Verification/VS-analysis-project-faq

**Comment by Lojovic** [comment]
The build and clean scripts have been separately added. Additionally, all the scripts have been changed as discussed on the project presentation. An issue has been opened regarding the possibility to improve the testing by writing a new main and testing targeted algorithms. Possible FAQs will be added as suggested.
